### ISSUE TITLE
Non functional app 

### ISSUE THREAD

**Issue by Inlustris** [xantari/Seq.App.Azure.DevOps#5]
Since the latest update of Seq we are not able to send tickets to DevOps. Is it possible for you to check this out.
It looks like it has to do something with the following package.
- Unable to load DLL 'System.IO.Compression.Native' 

The event event-3f4d01ef4ba308db5359447900000000 could not be sent to Azure Reporter.

[Event](https://seq.lyanthe.com/)Id
[event-3f4d01ef4ba308db5359447900000000](https://seq.lyanthe.com/#/events/?filter=@Id%20%3D%20'event-3f4d01ef4ba308db5359447900000000')
Seq.Apps.SeqAppException: Error while creating item in Azure DevOps. The step is: Connecting to Azure DevOps.
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load DLL 'System.IO.Compression.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.InflateInit2_(Int32 windowBits)
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at System.Net.Http.DecompressionHandler.GZipDecompressedContent.GetDecompressedStream(Stream originalStream)
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.CheckForServerUpdatesAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.FindServiceDefinitionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.LocationForCurrentConnectionAsync(String serviceType, Guid serviceIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.ResolveLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Seq.App.Azure.DevOps.AzureDevOpsReactor.CreateIssueAsync(Event`1 evt) in C:\projects\seq-app-azure-devops\src\Seq.App.Azure.DevOps\AzureDevOpsReactor.cs:line 181
   at Seq.App.Azure.DevOps.AzureDevOpsReactor.OnAsync(Event`1 evt) in C:\projects\seq-app-azure-devops\src\Seq.App.Azure.DevOps\AzureDevOpsReactor.cs:line 161
   --- End of inner exception stack trace ---
   at Seq.App.Azure.DevOps.AzureDevOpsReactor.OnAsync(Event`1 evt) in C:\projects\seq-app-azure-devops\src\Seq.App.Azure.DevOps\AzureDevOpsReactor.cs:line 170
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113

**Comment by Inlustris** [comment]
I have checked the dll is installed in the Seq Folder.

**Comment by nblumhardt** [comment]
Hi @Inlustris - just a note that reaching out to `support@datalust.co` with some details of your Seq install is worthwhile here, too.

**Comment by Inlustris** [comment]
Ok i will have a go at that to. 

If you find a solution on your side let me know. If i get a result from Datalust i will do the same.

**Comment by Inlustris** [comment]
It has been picked up by datalust. They are investigating the issue and will let me know if they find something.

**Comment by nblumhardt** [comment]
Sorry about the delay, I'm still on this and will update you here as soon as possible.

**Comment by nblumhardt** [comment]
I think I've found it! https://github.com/dotnet/runtime/issues/82518 - investigating further now.

Seq's installer includes some special logic to fix this issue _for the Seq.exe application_ but doesn't do the same for _Client/seqcli.exe_. My bet is that your `C:\Program Files\Seq\Client` folder is missing `System.IO.Compression.Native.dll`, or something related to it.

**Comment by nblumhardt** [comment]
I've confirmed that the issue above does occur when upgrading Seq from 2022.1 to 2023.1.

You can work around this by copying _System.IO.Compression.Native.dll_ from `C:\Program Files\Seq` to `C:\Program Files\Seq\Client`, then restarting the Seq process.

99.9% sure this will fix the problems with the app; if it doesn't, please let me know.

Thanks for reporting this!

**Comment by xantari** [comment]
@Inlustris Let us know if that workaround works and I will close the issue.

**Comment by Inlustris** [comment]
this does work, Thank you for finding out what the problem was.

**Comment by nblumhardt** [comment]
Tracking issue for the permanent fix: https://github.com/datalust/seq-tickets/issues/1840
